### ISSUE TITLE
setup.py won't work

### ISSUE THREAD

**Issue by soulware1** [Akascape/Datamosher-Pro#12]
log:
All folders available!
Some modules are not installed
 do you want to download and install them? (Y/N): Y
Installing modules...
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
ffgac/ffedit not found inside ffglitch folder, you cannot run the ffglitch modes without these programs
Do you want to download ffglitch now? (Y/N): Y
Downloading FFglitch...(size: approx 17MB)
Unable to download ffglitch from site! Check your connection or download it manually from https://github.com/Akascape/FFglitch-0.9.3-executables
and paste the files (ffgac and ffedit) inside FFglitch folder.
Something went wrong!
Setup Complete!

**Comment by Akascape** [comment]
@imadeagithubaccountforthis Please follow the manual setup: 
https://github.com/Akascape/Datamosher-Pro/wiki/1.How-to-Install#manual-setup

**Comment by Akascape** [comment]
@imadeagithubaccountforthis 
Install python properly by clicking the "add to path" option, here is a tutorial video: https://user-images.githubusercontent.com/89206401/187713564-fe75c20c-d457-431a-9332-511be7411218.mp4

After this, run setup.py.
if problem remains, then follow the manual setup guide: 
https://github.com/Akascape/Datamosher-Pro/wiki/1.How-to-Install#manual-setup
