### ISSUE TITLE
Version 2.1: CTkRangeSlider startup failure with python 3.8

### ISSUE THREAD

**Issue by radiophonic** [Akascape/Datamosher-Pro#14]
Hello, nice to see the update and thank you.

Just grabbed your latest commit, 2.1, however it fails to start with the following error:
```
Traceback (most recent call last):
  File "Datamosher Pro.py", line 20, in <module>
    from Assets.CTkRangeSlider import CTkRangeSlider
  File "/home/user/Tools/datamoshing-tools/Datamosher Pro/Assets/CTkRangeSlider/__init__.py", line 9, in <module>
    from .ctk_rangeslider import CTkRangeSlider
  File "/home/user/Tools/datamoshing-tools/Datamosher Pro/Assets/CTkRangeSlider/ctk_rangeslider.py", line 422, in <module>
    class CTkRangeSlider(CTkBaseClass):
  File "/home/user/Tools/datamoshing-tools/Datamosher Pro/Assets/CTkRangeSlider/ctk_rangeslider.py", line 743, in CTkRangeSlider
    def set(self, output_values: list[float], from_variable_callback=False):
TypeError: 'type' object is not subscriptable

```

Python 3.8.10 / Linux Mint 20.3 Una / base: Ubuntu 20.04 focal 

Cheers!

**Comment by Akascape** [comment]
@radiophonic Not a problem in python 3.9+ versions. [See here](https://stackoverflow.com/a/63460173/16813096)

Working fine with python 3.10 Ubuntu:
![Screenshot](https://github.com/Akascape/Datamosher-Pro/assets/89206401/eaf9520b-21db-4069-a494-4c3964fe45e4)

**Comment by Akascape** [comment]
@radiophonic Can you add this line in top of this [file](https://github.com/Akascape/Datamosher-Pro/blob/Datamosher-Pro-master/Python%20Version/Assets/CTkRangeSlider/ctk_rangeslider.py) and let me know if it fixes the issue.
```python
from __future__ import annotations
```

**Comment by radiophonic** [comment]
Apologies for the delay, I had a hard drive failure. I'll get to this tomorrow. :)

**Comment by radiophonic** [comment]
Following up. The current version is working well on Mint 21.2, thanks.

As a side note, the current version of python3-pil (pillow) is version 9 and causes your program to fail. However, installing pillow 10 via pip fixes the issue.

Have a good one and thanks again for the patience and, the software. :)
