### ISSUE TITLE
Unknow option -angle

### ISSUE THREAD

**Issue by petale-azerty** [Akascape/Datamosher-Pro#16]
Hello, I have an issue with the program. 

I'm on macOs and after running datamosher pro.py I have this issue 

File "/Users/****/.pyenv/versions/3.9.7/lib/python3.9/tkinter/__init__.py", line 2776, in _create
    return self.tk.getint(self.tk.call(
_tkinter.TclError: unknown option "-angle"

Everything worked fine during installation. 
If anyone can help me, would be wonderful.
thanks,
max

**Comment by Akascape** [comment]
@petale-azerty Try updating tkinter. `pip3 install tk --upgrade`

**Comment by petale-azerty** [comment]
Hello ! thank you so much it worked !! 
I'm gonna close the issue then.
