### ISSUE TITLE
FFglitch license?

### ISSUE THREAD

**Issue by KiwifruitDev** [Akascape/Datamosher-Pro#17]
The repository for Datamosher Pro is licensed under the MIT License, however ffglitch is (L)GPL which restricts commercial use when being distributed.
This seems misleading and I'm not sure how to properly attribute it if it were to be covered under MIT, which permits commercial use.
Does the paid Windows version distribute ffglitch?
If so, how is it licensed for a commercial product?
Please let me know, thank you.

**Comment by Akascape** [comment]
@KiwifruitDev I have already mentioned that 
>Note that FFglitch and FFmpeg are not provided in the releases and is not placed under this license (MIT). All the required licenses (mostly MIT) are provided in their folder/blocks respectively and it must be taken into account that multiple licenses are involved.

Datamosher_Pro.py and it's subparts are licensed as MIT which allows commercial use. However the application also uses ffmpeg and ffglitch which doesn't fall in MIT license (as mentioned above), so they are separately distributed.

FFglitch and FFmpeg are **not modified** at all, and it's source code is already available in public. FFglitch is a derivate work of ffmpeg, source code is here: https://github.com/ramiropolla/ffglitch-core (same license as ffmpeg). Both are used with dynamic linking.

And it's **not** written that we can't use it for commercial purposes. We can use it in any project, but we also have to **make the source code available to public if we modify it** (only that lgpl part), which is already there and Datamosher Pro follows that. That is the only condition.

Even the paid After effects plugin called Datamosh 2 uses ffglitch in it's core.

I hope this explains all the things. It is not at all misleading/violating licenses, you have to search all the documentation. Moreover, even in the exe version, those folders are clearly separated from the main application.

![IMG_20240528_102107.jpg](https://github.com/Akascape/Datamosher-Pro/assets/89206401/9ebed455-8e8b-4437-879a-a42c5029ce4a)

Datamosher Pro is also mentioned in the official ffglitch website: http://ffglitch.org/frontends/
