### ISSUE TITLE
Does Bloom not work at all?

### ISSUE THREAD

**Issue by leatherbird** [Akascape/Datamosher-Pro#3]
If I select Bloom, Datamosher Pro just hangs on "Converting the Video..." indefinitely.
Meanwhile a complete video file is created where no effect has been applied.

Also, most of the other Modes just bring the error "Please choose the video file again!"

I'm using Windows 10 Pro version 21H1 OS build 19043.1706

*Edit: actually now that I've tested it only "Classic" "Glide" "Echo" and "Sort" work at all.
Is there a possibility of getting a refund?

At present, this program doesn't seem to do anything.

**Comment by Akascape** [comment]
Bloom will take longer to mosh, use a short video and set kill frame to 0.5 or less.
Are the modes still not working after changing the directory? 
If you want refund then reply once... also tell me the email address you provided there.

**Comment by leatherbird** [comment]
I apologize. I thought I had deleted this.
Once I switched directories everything starting working, and working quite well.
(Just a minor misunderstanding about where to install.)
It is absolutely worth the price. No refund necessary. I very much appreciate your work on this project.

**Comment by Akascape** [comment]
Great, thanks for supporting the development.

For now I will just recommend you to read the two short guides available in my gumroad page for more details on the modes. Secondly a new and fresh update is coming soon. I am currently working on a modern GUI, new functionalities and custom conversion settings, and much more sorted stuff. 
Obviously without support projects cannot be improved. So thanks again for your kind support :)
