### ISSUE TITLE
Best Location for running this?

### ISSUE THREAD

**Issue by leatherbird** [Akascape/Datamosher-Pro#4]
I was unable to get any of the Modes to work.
Then, following the advice of someone on Reddit to move the .exe outside of a user folder I put it on a separate drive and BOOM, it started working.
I think there are many Permission issues that don't show up in your little script window.

You may want to make note of this.

**Comment by Akascape** [comment]
First of all, thanks for supporting and also for pointing this out, in programs like this you have to give administrative permissions (writing permissions) if you use it inside the user folder. But no need if you are using it in other directories. That's the case in windows. But I will take this note for the new version,

BTW I am working on a new version of Datamosher-Pro that will include a modern GUI and lots of functionalities,
when it's ready you will get it first. :)

You can give your feedback for the progress of the new interface:

![Screenshot 2022-05-29 200550](https://user-images.githubusercontent.com/89206401/170874886-d2c84f4e-fc1c-4fd8-a118-1f3189391a39.png)
(It will be available by the next month)

Thanks again, :) You are really awesome!

**Comment by Akascape** [comment]
First of all, thanks for pointing this out, in programs like this you have to give administrative permissions (writing permissions) if you use it inside the user folder. But no need if you are using it in other directories. That's the case in windows. But I will take this note for the new version.
