### ISSUE TITLE
ffmpeg: No such file or directory

### ISSUE THREAD

**Issue by sam959** [Akascape/Datamosher-Pro#9]
**Expected**: Running of script correctly
**Actual**: When hitting "mosh" after choosing video, this error presents:

/bin/sh: .../Projects/Datamosher Pro/ffmpeg: No such file or directory

Ffmpeg is installed. Suggestion on what I'm missing?
Thank you very much

**Comment by Akascape** [comment]
@sam959 Did you installed imageio-ffmpeg?

**Comment by Akascape** [comment]
@sam959 If it's installed then copy that imageio-ffmoeg folder to the Datamosher-pro folder. 

The path for that folder should be this: `python/lib/site-packages/imageio_ffmpeg`

If this is also not working then copy the ffmpeg file in Datamosher-Pro folder.

**Comment by Akascape** [comment]
@sam959, I have updated the code a bit. You can download the latest version:
https://github.com/Akascape/Datamosher-Pro/releases/download/Datamosher_Prov1.9/Datamosher-Pro_python-version_1.91.zip

**Comment by Akascape** [comment]
@sam959 Please let me know if the new version is working?
If it's still not working, then copy a ffmpeg file in Datamosher-Pro folder.

**Comment by sam959** [comment]
@Akascape Using the latest version you provided solved the issue for me. Thank you very much!
